export const SET_PLAYER_REQUEST = 'SET_PLAYER_REQUEST'
export const SET_PLAYER_SUCCESS = 'SET_PLAYER_SUCCESS'
export const SET_PLAYER_FAIL = 'SET_PLAYER_FAIL'

export const CONNECT_PLAYER_REQUEST = 'CONNECT_PLAYER_REQUEST'
export const CONNECT_PLAYER_SUCCESS = 'CONNECT_PLAYER_SUCCESS'
export const CONNECT_PLAYER_FAIL = 'CONNECT_PLAYER_FAIL'

export const SET_TRACK = 'SET_TRACK'
export const SET_PAUSE = 'SET_PAUSE'
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE'
