export const SET_PLAYER_REQUEST = 'SET_PLAYER_REQUEST'
export const SET_PLAYER_SUCCESS = 'SET_PLAYER_SUCCESS'
export const SET_PLAYER_FAIL = 'SET_PLAYER_FAIL'

export const CONNECT_PLAYER_REQUEST = 'CONNECT_PLAYER_REQUEST'
export const CONNECT_PLAYER_SUCCESS = 'CONNECT_PLAYER_SUCCESS'
export const CONNECT_PLAYER_FAIL = 'CONNECT_PLAYER_FAIL'

export const SET_TRACK = 'SET_TRACK'
export const SET_PAUSE = 'SET_PAUSE'
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE'

export const PLAY_SONG_REQUEST = 'PLAY_SONG_REQUEST'
export const PLAY_SONG_SUCCESS = 'PLAY_SONG_SUCCESS'
export const PLAY_SONG_FAIL = 'PLAY_SONG_FAIL'

export const TOGGLE_SHUFFLE_REQUEST = 'TOGGLE_SHUFFLE_REQUEST'
export const TOGGLE_SHUFFLE_SUCCESS = 'TOGGLE_SHUFFLE_SUCCESS'
export const TOGGLE_SHUFFLE_FAIL = 'TOGGLE_SHUFFLE_FAIL'
