export const GET_PLAYLIST_REQUEST = 'GET_PLAYLIST_REQUEST'
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS'
export const GET_PLAYLIST_FAIL = 'GET_PLAYLIST_FAIL'

export const GET_ARTIST_REQUEST = 'GET_ARTIST_REQUEST'
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS'
export const GET_ARTIST_FAIL = 'GET_ARTIST_FAIL'
